words_to_check:
  - elara
  - whispering woods
  - eldoria
models: 
  - Mistral-Nemo-12B-Instruct-2407
  - Meta-Llama-3.1-70B-Instruct
  - Llama-3.1-8B-ArliAI-RPMax-v1.1
  - Mistral-Nemo-12B-ArliAI-RPMax-v1.1
  - Llama-3.1-70B-ArliAI-RPMax-v1.1
api_key: API_KEY
llm_urls:
  - https://api.arliai.com
max_workers_per_url:
  - 6
