words_to_check:
  - elara
  - whispering woods
  - eldoria
models: 
  - Meta-Llama-3.1-8B-Instruct
api_key: you_api_key
llm_urls:
  - https://api.arliai.com/v1/completions
max_workers_per_url:
  - 24
